version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.0
jobs:
  build:
    docker:
      - image: circleci/python:3.10
    steps:
      - browser-tools/install-chrome
      - checkout
      - run:
          command: |
            google-chrome --version
      - run:
          name: Upgrade pip
          command: |
            pip install --upgrade pip
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Run Selenium Tests
          command: |
            export NPS_URL=${NPS_URL}
            pytest tests/test_0_start_staging.py --headless