env:
  NAME: ${{ secrets.START_WORKFLOW }}


name: Testing NP Mac

on:
  workflow_dispatch:
    inputs:
      my_value:
        description: 'My input value'
        required: true
        default: $NAME
        type: string
  repository_dispatch:
    types: [START]


permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade --upgrade-strategy eager seleniumbase names defusedxml pytest-md pytest-github-report fake_email random-password-generator 
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install Firefox
      run: |
        brew reinstall --cask firefox

    - name: Test
      run: |
        export NPS_PASS=${{ secrets.PASSWORD }}
        export NPS_EMAIL=${{ secrets.EMAIL }}
        export NPS_URL=${{ secrets.NPS_URL }}
        pytest tests/test_1_register.py --headless --github-report --dashboard -v --pls=none --sjw --firefox
        
        