env:
  NAME: ${{ secrets.START_WORKFLOW }}


name: Testing NP

on:
  schedule:
    - cron: '0 8 * * *'
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      my_value:
        description: 'My input value'
        required: true
        default: $NAME
        type: string
  repository_dispatch:
    types: [START]


permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade --upgrade-strategy eager seleniumbase names defusedxml genbadge  send_gmail pytest-md pytest-github-report
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test
      run: |
        export NPS_PASS=${{ secrets.PASSWORD }}
        export NPS_EMAIL=${{ secrets.EMAIL }}
        export NPS_URL=${{ secrets.NPS_URL }}
        pytest tests --headless --github-report --dashboard
        
    - name: Send Gmail
      run: |
        export RECEIVE_FROM_GMAIL=${{ secrets.RECEIVE_FROM_GMAIL }}
        export SEND_TO_GMAIL=${{ secrets.SEND_TO_GMAIL }}
        export GMAIL_PYTEST_CODE=${{ secrets.GMAIL_PYTEST_CODE }}
        python send_to_gmail.py
        